import 'package:flutter/material.dart';
import 'package:smart_design_system/smart_design_system.dart';

final defaultLightSmartColors = SmartColors(
  brightness: Brightness.light,
  primary: Color(0xff4f5b92),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffdde1ff),
  onPrimaryContainer: Color(0xff374379),
  secondary: Color(0xff5a5d72),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffdfe1f9),
  onSecondaryContainer: Color(0xff424659),
  info: Color(0xff76546e),
  onInfo: Color(0xffffffff),
  infoContainer: Color(0xffffd7f3),
  onInfoContainer: Color(0xff5c3d56),
  error: Color(0xffba1a1a),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffffdad6),
  onErrorContainer: Color(0xff93000a),
  success: Color(0xff4b662c),
  onSuccess: Color(0xffffffff),
  successContainer: Color(0xffcdeda4),
  onSuccessContainer: Color(0xff354e16),
  warning: Color(0xff8c4f26),
  onWarning: Color(0xffffffff),
  warningContainer: Color(0xffffdbc8),
  onWarningContainer: Color(0xff6f3811),
  background: Color(0xfffbf8ff),
  onBackground: Color(0xff1b1b21),
  outline: Color(0xff767680),
  disabled: Color(0xffdbd9e0),
  onDisabled: Color(0xff767680),
  card: Color(0xffefedf4),
  cardHigh: Color(0xffe9e7ef),
  cardLow: Color(0xfff5f2fa),
);

final defaultDarkSmartColors = SmartColors(
  brightness: Brightness.dark,
  primary: Color(0xffb8c3ff),
  onPrimary: Color(0xff202c61),
  primaryContainer: Color(0xff374379),
  onPrimaryContainer: Color(0xffdde1ff),
  secondary: Color(0xffc3c5dd),
  onSecondary: Color(0xff2c2f42),
  secondaryContainer: Color(0xff424659),
  onSecondaryContainer: Color(0xffdfe1f9),
  info: Color(0xffe4bad9),
  onInfo: Color(0xff44273e),
  infoContainer: Color(0xff5c3d56),
  onInfoContainer: Color(0xffffd7f3),
  error: Color(0xffffb4ab),
  onError: Color(0xff690005),
  errorContainer: Color(0xff93000a),
  onErrorContainer: Color(0xffffdad6),
  success: Color(0xffb1d18a),
  onSuccess: Color(0xff1f3701),
  successContainer: Color(0xff354e16),
  onSuccessContainer: Color(0xffcdeda4),
  warning: Color(0xffffb68b),
  onWarning: Color(0xff522300),
  warningContainer: Color(0xff6f3811),
  onWarningContainer: Color(0xffffdbc8),
  background: Color(0xff121318),
  onBackground: Color(0xffe3e1e9),
  outline: Color(0xffb1b1bb),
  disabled: Color(0xffdbd9e0),
  onDisabled: Color(0xff767680),
  card: Color(0xff1f1f25),
  cardHigh: Color(0xff292a2f),
  cardLow: Color(0xff1b1b21),
);

// static const lightMainScheme = ColorScheme(
//     brightness: Brightness.light,
//     primary: Color(0xFF1BB17A),
//     onPrimary: Color(0xFFFFFFFF),
//     primaryContainer: Color(0xFFA8E6CF),
//     onPrimaryContainer: Color(0xFF083323),
//     secondary: Color(0xFF7B9786),
//     onSecondary: Color(0xFFFFFFFF),
//     secondaryContainer: Color(0xFFD8E6DE),
//     onSecondaryContainer: Color(0xFF29332D),
//     tertiary: Color(0xFF6898AA),
//     onTertiary: Color(0xFFFFFFFF),
//     tertiaryContainer: Color(0xFFC9DEE6),
//     onTertiaryContainer: Color(0xFF1F2D33),
//     error: Color(0xFFB3261E),
//     onError: Color(0xFFFFFFFF),
//     errorContainer: Color(0xFFE6ACA9),
//     onErrorContainer: Color(0xFF330B09),
//     surface: Color(0xFFf5fbf4),
//     onSurface: Color(0xFF171d19),
//     surfaceContainerHighest: Color(0xFFdee4de),
//     surfaceContainerHigh: Color(0xFFe4eae3),
//     surfaceContainer: Color(0xFFeaefe9),
//     surfaceContainerLow: Color(0xFFf0f5ef),
//     surfaceContainerLowest: Color(0xFFffffff),
//     onSurfaceVariant: Color(0xFF404943),
//     outline: Color(0xFF707972),
//     outlineVariant: Color(0xFFc0c9c1),
//   );
