import 'package:flutter/material.dart';

abstract class SmartColors {
  static const ColorScheme deafultScheme = SmartColors.lightMainScheme;
  static const lightMainScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1BB17A),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFA8E6CF),
    onPrimaryContainer: Color(0xFF083323),
    secondary: Color(0xFF7B9786),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD8E6DE),
    onSecondaryContainer: Color(0xFF29332D),
    tertiary: Color(0xFF6898AA),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC9DEE6),
    onTertiaryContainer: Color(0xFF1F2D33),
    error: Color(0xFFB3261E),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFE6ACA9),
    onErrorContainer: Color(0xFF330B09),
    surface: Color(0xFFf5fbf4),
    onSurface: Color(0xFF171d19),
    surfaceContainerHighest: Color(0xFFdee4de),
    surfaceContainerHigh: Color(0xFFe4eae3),
    surfaceContainer: Color(0xFFeaefe9),
    surfaceContainerLow: Color(0xFFf0f5ef),
    surfaceContainerLowest: Color(0xFFffffff),
    onSurfaceVariant: Color(0xFF404943),
    outline: Color(0xFF707972),
    outlineVariant: Color(0xFFc0c9c1),
  );

  static const darkMainScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF8fd5af),
    onPrimary: Color(0xFF003823),
    primaryContainer: Color(0xFF005235),
    onPrimaryContainer: Color(0xFFaaf2ca),
    secondary: Color(0xFFb4ccbc),
    onSecondary: Color(0xFF203529),
    secondaryContainer: Color(0xFF364b3f),
    onSecondaryContainer: Color(0xFFd0e8d8),
    tertiary: Color(0xFFc0e9fa),
    onTertiary: Color(0xFF063542),
    tertiaryContainer: Color(0xFF234c5a),
    onTertiaryContainer: Color(0xFFc0e9fa),
    error: Color(0xFFE69490),
    onError: Color(0xFF4C100D),
    errorContainer: Color(0xFF661511),
    onErrorContainer: Color(0xFFE6ACA9),
    surface: Color(0xFF0f1511),
    onSurface: Color(0xFFdee4de),
    surfaceContainerHighest: Color(0xFF303632),
    surfaceContainerHigh: Color(0xFF262b27),
    surfaceContainer: Color(0xFF1b211d),
    surfaceContainerLow: Color(0xFF171d19),
    surfaceContainerLowest: Color(0xFF0a0f0c),
    onSurfaceVariant: Color(0xFFc0c9c1),
    outline: Color(0xFF8a938c),
    outlineVariant: Color(0xFF404943),
  );
}
